# This file contains configuration specific for this repository that are different from the default Ekylibre style guide

inherit_from: https://gitlab.com/ekylibre/tools/rubocop/-/raw/0.1.0/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'

Naming/MethodName:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'test/**/*'